// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/v1/ingest.proto

package ingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogRecord represents a single log entry sent by the agent.
type LogRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix timestamp in nanoseconds.
	TimestampNs int64  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Message     string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Level       string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Feature-aware observability fields.
	Service string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Feature string `protobuf:"bytes,5,opt,name=feature,proto3" json:"feature,omitempty"`
	TraceId string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId  string `protobuf:"bytes,7,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Source tracking.
	Source    string `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Container string `protobuf:"bytes,9,opt,name=container,proto3" json:"container,omitempty"`
	// Arbitrary key-value metadata attached by enrichment.
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_proto_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRecord) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogRecord) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *LogRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogRecord) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LogRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogsRequest) Reset() {
	*x = SendLogsRequest{}
	mi := &file_proto_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogsRequest) ProtoMessage() {}

func (x *SendLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogsRequest.ProtoReflect.Descriptor instead.
func (*SendLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *SendLogsRequest) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type SendLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of records accepted by the backend.
	Accepted      int32 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogsResponse) Reset() {
	*x = SendLogsResponse{}
	mi := &file_proto_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogsResponse) ProtoMessage() {}

func (x *SendLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogsResponse.ProtoReflect.Descriptor instead.
func (*SendLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *SendLogsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_proto_v1_ingest_proto protoreflect.FileDescriptor

const file_proto_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/ingest.proto\x12\x16featuretrace.ingest.v1\"\x86\x03\n" +
	"\tLogRecord\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x18\n" +
	"\afeature\x18\x05 \x01(\tR\afeature\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\a \x01(\tR\x06spanId\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x1c\n" +
	"\tcontainer\x18\t \x01(\tR\tcontainer\x12K\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2/.featuretrace.ingest.v1.LogRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x0fSendLogsRequest\x12;\n" +
	"\arecords\x18\x01 \x03(\v2!.featuretrace.ingest.v1.LogRecordR\arecords\".\n" +
	"\x10SendLogsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted2n\n" +
	"\rIngestService\x12]\n" +
	"\bSendLogs\x12'.featuretrace.ingest.v1.SendLogsRequest\x1a(.featuretrace.ingest.v1.SendLogsResponseB'Z%featuretrace.io/app/proto/v1;ingestv1b\x06proto3"

var (
	file_proto_v1_ingest_proto_rawDescOnce sync.Once
	file_proto_v1_ingest_proto_rawDescData []byte
)

func file_proto_v1_ingest_proto_rawDescGZIP() []byte {
	file_proto_v1_ingest_proto_rawDescOnce.Do(func() {
		file_proto_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_ingest_proto_rawDesc), len(file_proto_v1_ingest_proto_rawDesc)))
	})
	return file_proto_v1_ingest_proto_rawDescData
}

var file_proto_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_ingest_proto_goTypes = []any{
	(*LogRecord)(nil),        // 0: featuretrace.ingest.v1.LogRecord
	(*SendLogsRequest)(nil),  // 1: featuretrace.ingest.v1.SendLogsRequest
	(*SendLogsResponse)(nil), // 2: featuretrace.ingest.v1.SendLogsResponse
	nil,                      // 3: featuretrace.ingest.v1.LogRecord.MetadataEntry
}
var file_proto_v1_ingest_proto_depIdxs = []int32{
	3, // 0: featuretrace.ingest.v1.LogRecord.metadata:type_name -> featuretrace.ingest.v1.LogRecord.MetadataEntry
	0, // 1: featuretrace.ingest.v1.SendLogsRequest.records:type_name -> featuretrace.ingest.v1.LogRecord
	1, // 2: featuretrace.ingest.v1.IngestService.SendLogs:input_type -> featuretrace.ingest.v1.SendLogsRequest
	2, // 3: featuretrace.ingest.v1.IngestService.SendLogs:output_type -> featuretrace.ingest.v1.SendLogsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_ingest_proto_init() }
func file_proto_v1_ingest_proto_init() {
	if File_proto_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_ingest_proto_rawDesc), len(file_proto_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_ingest_proto_goTypes,
		DependencyIndexes: file_proto_v1_ingest_proto_depIdxs,
		MessageInfos:      file_proto_v1_ingest_proto_msgTypes,
	}.Build()
	File_proto_v1_ingest_proto = out.File
	file_proto_v1_ingest_proto_goTypes = nil
	file_proto_v1_ingest_proto_depIdxs = nil
}
